### ISSUE TITLE
This service has been suspended.

### ISSUE THREAD

**Issue by helmut-hoffer-von-ankershoffen** [eggplants/ghcr-badge#195]
https://ghcr-badge.egpl.dev/ leads to "This service has been suspended."

Worked a few days ago. Is this expected?

**Comment by eggplants** [comment]
Deployment of this app is running on Render.com's free plan and often stops working at the end of the month due to the free quota. Please sponsor me for 19 USD per month, or self-host yourself.

**Comment by eggplants** [comment]
[Free instance hours](https://render.com/docs/free#free-instance-hours).
