### ISSUE TITLE
mono repository support

### ISSUE THREAD

**Issue by evantill** [eggplants/ghcr-badge#56]
Hi, 

Thank you for thoses badges : really cool 😍 .

We have a mono repository with multiple containers :

https://github.com/orgs/plantuml/packages?repo_name=docker

Is it possible to create a badge for each package ?
I have not managed to find a solution.

**Comment by eggplants** [comment]
Maybe: https://github.com/pallets/flask/issues/900

I'll try to find proper workaround and fix.

**Comment by eggplants** [comment]
<https://ghcr-badge.egpl.dev/plantuml/docker/jekyll/tags?trim=major>

![jekyll](https://ghcr-badge.egpl.dev/plantuml/docker/jekyll/tags?trim=major)

<https://ghcr-badge.egpl.dev/plantuml/docker/graalvm/tags?trim=major>

![graalvm](https://ghcr-badge.egpl.dev/plantuml/docker/graalvm/tags?trim=major)

**Comment by evantill** [comment]
Wonderfull. Thank you very much.
