### ISSUE TITLE
Support for GitHub releases pre-release tags

### ISSUE THREAD

**Issue by ptr727** [eggplants/ghcr-badge#7]
See: https://github.com/ptr727/PlexCleaner/issues/100
And: https://github.com/badges/shields/issues/7913

Desire to have a deterministic badge for latest pre-release GitHub release.
Standard shields.io badge works as long as pre-release build is later than release build.
As soon as release build version is later than pre-release version the pre-release tag badge becomes a release badge.

Desire to have a badge for latest release, and latest pre-release, even if release version is later than pre-release version.

**Comment by eggplants** [comment]
Pre-release or not cannot be determined from DockerAPI information alone, and such tagging is not in the specification, so it will not be supported for the time being...

Sorry, and thank you!

**Comment by ptr727** [comment]
> Pre-release or not cannot be determined from DockerAPI information alone

This request is for GitHub releases, not Docker?

**Comment by eggplants** [comment]
Isn't it? I didn't understand the situation very well, so can you give me a specific example?

**Comment by eggplants** [comment]
Ah, this was not originally about Ghcr, but about GitHub pre-releases. I didn't read the original Issue carefully.
