### ISSUE TITLE
Wrong version number 

### ISSUE THREAD

**Issue by kroese** [eggplants/ghcr-badge#71]
When using the badge, it remove the last zero for version numbers.

For example, 1.19 is displayed as 1.19, but 1.20 will be displayed as 1.2. This is a bit confusing, because my minor numbers are simply incrementing, so 1.2 is an older version, and not the same as 1.20.

**Comment by eggplants** [comment]
> For example, 1.19 is displayed as 1.19, but 1.20 will be displayed as 1.2. 

@kroese For debugging, please provide the real-world example you met.

**Comment by eggplants** [comment]
<https://ghcr-badge.deta.dev/qemu-tools/qemu-docker/tags?n=1&label=version&color=SteelBlue&ignore=1.93,1.92,1.91>

![](https://ghcr-badge.deta.dev/qemu-tools/qemu-docker/tags?n=1&label=version&color=SteelBlue&ignore=1.93,1.92,1.91)

**Comment by eggplants** [comment]
This is a bit strange behaviour...

![n=1](https://ghcr-badge.deta.dev/qemu-tools/qemu-docker/tags?n=1&label=version&color=SteelBlue&ignore=1.96,1.95,1.94,1.93,1.92,1.91)

![n=2](https://ghcr-badge.deta.dev/qemu-tools/qemu-docker/tags?n=2&label=version&color=SteelBlue&ignore=1.96,1.95,1.94,1.93,1.92,1.91)

**Comment by eggplants** [comment]
It might be a bug of anybadge. `print(anybadge.Badge(label="test", value="1.20").badge_svg_text, file=open("a.svg", "w"))` outputs:

![a](https://user-images.githubusercontent.com/42153744/235949036-a260e341-8acc-4f8f-9d80-931a41a0d652.svg)
